export const apartments = {
    1: {
        name: "Emperor Apartment 1",
        id: 3069140,
        bedrooms: 1,
        tvSize: 75,
        squareFeet: 700,
        bathrooms: 2,
        maxGuests: 6,
        amountOfPictures: 8,
        
    },
    2: {
        name: "Emperor Apartment 2",
        id: 3070529,
        bedrooms: 1,
        tvSize: 75,
        squareFeet: 646,
        bathrooms: 2,
        maxGuests: 6,
        amountOfPictures: 9,
    },
    3: {
        name: "Emperor Studio Apartment 3",
        id: 3070530,
        bedrooms: 0,
        tvSize: 55,
        squareFeet: 355,
        bathrooms: 1,
        maxGuests: 4,
        amountOfPictures: 3,
    },
    4: {
        name: "King Studio Apartment 4",
        id: 3070531,
        bedrooms: 0,
        tvSize: 43,
        squareFeet: 301,
        bathrooms: 1,
        maxGuests: 3,
        amountOfPictures: 4,
    },
    5: {
        name: "King Studio Apartment 5",
        id: 3070533,
        bedrooms: 0,
        tvSize: 43,
        squareFeet: 269,
        bathrooms: 1,
        maxGuests: 4,
        amountOfPictures: 4,
    },
    6: {
        name: "Emperor Apartment 6",
        id: 3070534,
        bedrooms: 1,
        tvSize: 75,
        squareFeet: 700,
        bathrooms: 2,
        maxGuests: 6,
        amountOfPictures: 8,
    },
    7: {
        name: "Emperor Apartment 7",
        id: 3070536,
        bedrooms: 1,
        tvSize: 75,
        squareFeet: 581,
        bathrooms: 2,
        maxGuests: 4,
        amountOfPictures: 7,
    },
    8: {
        name: "The Cottage Apartment 8",
        id: 3070537,
        bedrooms: 2,
        tvSize: 55,
        squareFeet: 560,
        bathrooms: 2,
        maxGuests: 6,
        amountOfPictures: 6,

    },
    9: {
        name: "King Studio Apartment 9",
        id: 3070540,
        bedrooms: 0,
        tvSize: 55,
        squareFeet: 388,
        bathrooms: 1,
        maxGuests: 4,
        amountOfPictures: 7,
    },
    10: {
        name: "The Cottage Apartment 10",
        id: 3070538,
        bedrooms: 2,
        tvSize: 55,
        squareFeet: 560,
        bathrooms: 2,
        maxGuests: 6,
        amountOfPictures: 8,
    }

};